# Generated by Django 3.1 on 2020-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='bedNum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='nric',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='patientName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phoneNum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='wardNum',
            field=models.TextField(default=''),
        ),
    ]
